### ISSUE TITLE
Is this board design compatible with ZU27DR or Gen 3 RFSOC like ZU47DR?

### ISSUE THREAD

**Issue by liubenyuan** [Xilinx/RFSoC2x2-PYNQ#35]
Hi, Is this board design compatible with ZU27DR or Gen 3 RFSOC like ZU47DR? That both are FFVG1517 footprints.

**Comment by schelleg** [comment]
This is a good question for the discuss.pynq.io forum ... if you're interested in building your own board, a great topic to put up.
